# Generated by Django 4.1.7 on 2023-02-15 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('chatmember_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.chatmember')),
                ('phone', models.CharField(max_length=10, unique=True, verbose_name='Номер телефона')),
                ('online', models.BooleanField(verbose_name='Онлайн')),
            ],
            bases=('chat.chatmember',),
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('chatmember_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.chatmember')),
                ('out_id', models.IntegerField(verbose_name='ID на портале')),
                ('clients', models.ManyToManyField(to='chat.client')),
            ],
            bases=('chat.chatmember',),
        ),
    ]
