# Generated by Django 4.1.7 on 2023-02-15 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatmember_name_alter_chatmember_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='operator',
            name='clients',
        ),
        migrations.AddField(
            model_name='chatmember',
            name='picture',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL на аватарку'),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время сообщения')),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chat')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatmember')),
            ],
        ),
        migrations.AddField(
            model_name='chatmember',
            name='chats',
            field=models.ManyToManyField(to='chat.chat'),
        ),
    ]
