# Generated by Django 4.1.7 on 2023-02-15 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_remove_operator_clients_chatmember_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chat_id',
            new_name='chat',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
