# Generated by Django 4.1.7 on 2023-02-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_chat_id_message_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='owner_type',
            field=models.CharField(default='client', max_length=10),
        ),
        migrations.AddField(
            model_name='operator',
            name='owner_type',
            field=models.CharField(default='client', max_length=10),
        ),
    ]
