# Generated by Django 4.1.7 on 2023-02-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_client_owner_type_remove_operator_owner_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='out_id',
            field=models.IntegerField(unique=True, verbose_name='ID на портале'),
        ),
    ]
