# Generated by Django 4.1.7 on 2023-02-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_client_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mobile_token',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Токен мобильного приложения'),
        ),
    ]
