# Generated by Django 4.1.7 on 2023-03-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_client_mobile_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField(verbose_name='ID линии на портале')),
            ],
        ),
    ]
