# Generated by Django 4.1.7 on 2023-03-21 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='online',
        ),
    ]
