# Generated by Django 4.1.7 on 2023-04-07 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_member_real_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('member_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.member')),
                ('connections', models.IntegerField(default=0, verbose_name='Кол-во соединений по сокету')),
                ('phone', models.CharField(max_length=10, unique=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('mobile_token', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Токен мобильного приложения')),
            ],
            options={
                'abstract': False,
            },
            bases=('main.member',),
        ),
    ]
