# Generated by Django 4.1.7 on 2023-04-07 22:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_update_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Последнее обновление из CRM'),
            preserve_default=False,
        ),
    ]
