# Generated by Django 4.1.7 on 2023-04-07 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prtl_Client',
            fields=[
                ('member_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.member')),
                ('phone', models.CharField(max_length=10, unique=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('mobile_token', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Токен мобильного приложения')),
                ('connections', models.IntegerField(default=0, verbose_name='Кол-во соединений по сокету')),
            ],
            bases=('main.member',),
        ),
        migrations.CreateModel(
            name='prtl_Line',
            fields=[
                ('line_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.line')),
                ('portal_line_id', models.IntegerField(blank=True, null=True, verbose_name='ID привязанной линии на портале')),
                ('icon', models.ImageField(upload_to='uploads/lines/icons/', verbose_name='Иконка для портала')),
            ],
            bases=('main.line',),
        ),
        migrations.CreateModel(
            name='prtl_Operator',
            fields=[
                ('member_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.member')),
                ('portal_user_id', models.IntegerField(unique=True, verbose_name='ID на портале')),
            ],
            bases=('main.member',),
        ),
    ]
