# Generated by Django 4.1.7 on 2023-04-07 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prtl_Client',
        ),
    ]
